name: 'Android CI/CD'
description: 'Build your Android application and update it in the store'
inputs:
  package-name:
    description: "The Android package name from the app manifest"
    required: true
  keystore:
    description: 'Base64 encoded Android keystore'
    required: true
  play-store-creds:
    description: 'Your Play Store credentials'
    required: true
  push-changes:
    description: 'Whether commit and push the created fastlane configuration'
    required: false
    default: false
  git-user-name:
    description: 'Required when push-changes is set, the git user.name'
    required: false
  git-user-email:
    description: 'Required when push-changes is set, the git user.email'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-name }}
    - ${{ inputs.keystore }}
    - ${{ inputs.play-store-creds }}
    - ${{ inputs.push-changes }}
    - ${{ inputs.git-user-name }}
    - ${{ inputs.git-user-email }}
