name: 'Android CI/CD'
description: 'Build your Android application and update it in the store'
inputs:
  package-name:
    description: "The Android package name from the app manifest"
    required: true
  keystore:
    description: 'Base64 encoded Android keystore'
    required: true
  play-store-creds:
    description: 'Your Play Store credentials'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.package-name }}
    - ${{ inputs.keystore }}
    - ${{ inputs.play-store-creds }}
